import {
  COMMON_AUDIENCE as A, COMMON_FAQS, COMMON_WHY, DEFAULT_COMPARISON, DEFAULT_INSTRUCTOR,
} from "./shared";
import type { Course } from "./types";

/**
 * The catalogue.
 *
 * Adding a course means appending one object here — the route, the template,
 * the sitemap and the related-course links all pick it up automatically. No
 * new page file is ever needed.
 *
 * Reviews below are drawn from the testimonials already on the site. Replace
 * them with the real, attributed reviews for each programme before launch.
 */

export const COURSES: Course[] = [
  /* ------------------------------------------------------------------ */
  {
    slug: "full-stack-web-development",
    title: "Full Stack Web Development",
    shortDescription:
      "Front to back, database to deploy — build and ship complete web applications.",
    overview:
      "A six-month programme that takes you from your first HTML page to a deployed, database-backed application. You write the front end, the API and the data layer, then put the whole thing online under code review.",
    category: "Web Development",
    level: "Beginner to Advanced",
    duration: "6 Months",
    mode: "Online / Offline",
    certification: true,
    heroImage: "/images/mern.webp",
    video: {
      url: "",
      thumbnail: "/images/classroom.webp",
      caption: "See how the programme runs, module by module.",
    },
    rating: { score: 4.9, count: 214 },
    audience: [A.beginners, A.students, A.freshers, A.switchers, A.freelancers],
    whyChooseUs: COMMON_WHY,
    modules: [
      {
        title: "HTML & CSS Fundamentals",
        summary: "Structure and style, done properly — semantics, layout and responsive design.",
        topics: ["Semantic HTML", "Flexbox & Grid", "Responsive design", "Accessibility basics"],
        duration: "3 weeks",
        lessons: 12,
      },
      {
        title: "JavaScript",
        summary: "The language itself, then the browser APIs you use it through.",
        topics: ["Types & scope", "Arrays and objects", "DOM & events", "Async, promises, fetch"],
        duration: "5 weeks",
        lessons: 20,
      },
      {
        title: "React",
        summary: "Component thinking, state, and the patterns real applications use.",
        topics: ["Components & props", "State & hooks", "Routing", "Data fetching & caching"],
        duration: "5 weeks",
        lessons: 18,
      },
      {
        title: "Node.js & Express",
        summary: "Server-side JavaScript: routing, middleware, authentication and file handling.",
        topics: ["HTTP & REST", "Express routing", "JWT auth", "Error handling"],
        duration: "4 weeks",
        lessons: 16,
      },
      {
        title: "MongoDB",
        summary: "Modelling data for an application that has to change over time.",
        topics: ["Schema design", "Mongoose", "Aggregation", "Indexes & performance"],
        duration: "3 weeks",
        lessons: 12,
      },
      {
        title: "Project Development & Deployment",
        summary: "Take one application from brief to production, with review at each stage.",
        topics: ["Git workflow", "Testing basics", "CI & environment config", "Deployment"],
        duration: "4 weeks",
        lessons: 14,
      },
    ],
    learningOutcomes: [
      "Build responsive websites that hold up on any screen",
      "Develop complete applications front to back",
      "Design and consume REST APIs",
      "Model and query a database",
      "Use Git and GitHub the way a team does",
      "Debug across the browser, server and database",
      "Deploy and configure an application for production",
    ],
    tools: ["HTML", "CSS", "JavaScript", "React", "Node.js", "Express", "MongoDB", "Git", "GitHub", "VS Code", "Postman", "Vercel"],
    careerOutcomes: {
      roles: ["Frontend Developer", "Backend Developer", "Full Stack Developer", "Web Developer", "MERN Developer"],
      opportunities: ["Product companies and startups", "Agency and client work", "Freelance web projects", "Internal tooling teams"],
      nextSteps: ["Next.js and server components", "TypeScript in depth", "Cloud & DevOps", "System design fundamentals"],
      industries: ["SaaS products", "E-commerce", "EdTech", "Enterprise applications"],
    },
    projects: [
      {
        name: "E-commerce storefront",
        summary: "Catalogue, cart, checkout flow and an admin view, backed by a real database.",
        tech: ["React", "Node.js", "MongoDB", "Stripe test mode"],
        level: "Advanced",
        skills: ["State management", "API design", "Payments", "Auth"],
        image: "/images/mern.webp",
      },
      {
        name: "Job portal",
        summary: "Listings, applications and role-based dashboards for seekers and recruiters.",
        tech: ["React", "Express", "MongoDB", "JWT"],
        level: "Intermediate",
        skills: ["Role-based access", "Search & filters", "File upload"],
        image: "/images/form.webp",
      },
      {
        name: "Admin dashboard",
        summary: "Charts, tables and CRUD over a live API, built to a supplied design.",
        tech: ["React", "REST", "Charting"],
        level: "Intermediate",
        skills: ["Data visualisation", "Forms", "Pagination"],
        image: "/images/data-science.webp",
      },
      {
        name: "Personal portfolio",
        summary: "Your own deployed site — the first thing an interviewer opens.",
        tech: ["HTML", "CSS", "JavaScript", "Vercel"],
        level: "Beginner",
        skills: ["Responsive layout", "Performance", "Deployment"],
        image: "/images/lab.webp",
      },
    ],
    instructor: DEFAULT_INSTRUCTOR,
    comparison: DEFAULT_COMPARISON,
    reviews: [
      {
        name: "Harmanpreet Singh",
        initials: "HS",
        rating: 5,
        course: "Full Stack Web Development",
        role: "Placed as MERN Developer",
        quote:
          "I walked in with a commerce degree and no idea what an API was. Three deployed projects and a clean commit history did more for me in interviews than any certificate.",
      },
      {
        name: "Simranjeet Kaur",
        initials: "SK",
        rating: 5,
        course: "Full Stack Web Development",
        role: "Frontend Developer",
        quote:
          "The code reviews were relentless in the best way. By the last module I was reading other people's pull requests without flinching.",
      },
      {
        name: "Aditya Malhotra",
        initials: "AM",
        rating: 5,
        course: "Full Stack Web Development",
        role: "Web Developer",
        quote:
          "Starting the project floor in month two was the difference. I stopped learning about development and started doing it.",
      },
    ],
    faqs: [
      {
        q: "Is this course suitable for beginners?",
        a: "Yes. The first two modules assume no prior coding, and the pace is set so fundamentals are solid before React arrives.",
      },
      {
        q: "What are the prerequisites?",
        a: "Basic computer familiarity. No prior programming, and no particular degree, is required.",
      },
      ...COMMON_FAQS,
      {
        q: "What can I do after completing the course?",
        a: "Graduates typically target frontend, backend or full stack developer roles, and some take on freelance client work with the portfolio they build here.",
      },
    ],
    relatedCourses: ["mern-stack-development", "python-programming", "java-programming", "data-analytics"],
    keywords: ["full stack developer course", "web development training Hoshiarpur", "MERN course", "React Node MongoDB training"],
  },

  /* ------------------------------------------------------------------ */
  {
    slug: "mern-stack-development",
    title: "MERN Stack Development",
    shortDescription: "MongoDB, Express, React and Node — one language, end to end.",
    overview:
      "Five months on the JavaScript stack most Indian product teams hire for. You build in React, serve with Express, store in MongoDB, and ship the result with authentication, tests and a deployment pipeline.",
    category: "Web Development",
    level: "Intermediate",
    duration: "5 Months",
    mode: "Online / Offline",
    certification: true,
    heroImage: "/images/form.webp",
    video: {
      url: "",
      thumbnail: "/images/lab.webp",
      caption: "A walkthrough of the stack and the projects you build on it.",
    },
    rating: { score: 4.9, count: 168 },
    audience: [A.students, A.freshers, A.professionals, A.switchers, A.freelancers],
    whyChooseUs: COMMON_WHY,
    modules: [
      {
        title: "JavaScript & ES6+ refresher",
        summary: "The language features the rest of the stack leans on.",
        topics: ["Modules", "Destructuring", "Async/await", "Functional patterns"],
        duration: "2 weeks",
        lessons: 8,
      },
      {
        title: "React in depth",
        summary: "Beyond the basics: composition, performance and real data flows.",
        topics: ["Hooks in anger", "Context & state libraries", "Routing", "Forms & validation"],
        duration: "5 weeks",
        lessons: 20,
      },
      {
        title: "Node.js & Express",
        summary: "APIs that other people can depend on.",
        topics: ["REST design", "Middleware", "Auth & sessions", "Rate limiting"],
        duration: "4 weeks",
        lessons: 16,
      },
      {
        title: "MongoDB & Mongoose",
        summary: "Schema design for applications that keep changing.",
        topics: ["Documents & relations", "Aggregation pipeline", "Indexing", "Transactions"],
        duration: "3 weeks",
        lessons: 12,
      },
      {
        title: "Testing & tooling",
        summary: "The habits that make a codebase survivable.",
        topics: ["Unit testing", "API testing", "Linting & formatting", "Debugging"],
        duration: "2 weeks",
        lessons: 8,
      },
      {
        title: "Capstone & deployment",
        summary: "One substantial application, reviewed and shipped.",
        topics: ["Architecture", "CI", "Environment config", "Monitoring basics"],
        duration: "4 weeks",
        lessons: 14,
      },
    ],
    learningOutcomes: [
      "Build production-shaped React applications",
      "Design and secure REST APIs with Express",
      "Model data in MongoDB and query it efficiently",
      "Implement authentication and role-based access",
      "Write tests that catch real regressions",
      "Deploy a full stack application end to end",
    ],
    tools: ["React", "Node.js", "Express", "MongoDB", "Mongoose", "JavaScript", "Git", "GitHub", "Postman", "Jest", "VS Code", "Vercel"],
    careerOutcomes: {
      roles: ["MERN Stack Developer", "React Developer", "Node.js Developer", "Full Stack Engineer", "Software Engineer"],
      opportunities: ["Product startups", "Agency delivery teams", "Freelance application builds", "Remote contract work"],
      nextSteps: ["TypeScript", "Next.js", "Cloud & DevOps", "System design"],
      industries: ["SaaS", "Fintech", "E-commerce", "Internal enterprise tooling"],
    },
    projects: [
      {
        name: "Social feed application",
        summary: "Posts, follows, notifications and an activity feed with real-time updates.",
        tech: ["React", "Node.js", "MongoDB", "WebSockets"],
        level: "Advanced",
        skills: ["Real-time data", "Feed ranking", "Optimistic UI"],
        image: "/images/mern.webp",
      },
      {
        name: "Booking platform",
        summary: "Availability, reservations and an operator dashboard.",
        tech: ["React", "Express", "MongoDB"],
        level: "Intermediate",
        skills: ["Date handling", "Conflict resolution", "Admin flows"],
        image: "/images/form.webp",
      },
      {
        name: "REST API with auth",
        summary: "A documented API with tokens, refresh flow and rate limiting.",
        tech: ["Node.js", "Express", "JWT"],
        level: "Intermediate",
        skills: ["API design", "Security", "Documentation"],
        image: "/images/cloud.webp",
      },
    ],
    instructor: DEFAULT_INSTRUCTOR,
    comparison: DEFAULT_COMPARISON,
    reviews: [
      {
        name: "Navjot Kaur",
        initials: "NK",
        rating: 5,
        course: "MERN Stack Development",
        role: "React Developer",
        quote:
          "The capstone was the closest thing to a real job I had done. Architecture decisions, review comments, the lot.",
      },
      {
        name: "Rohit Verma",
        initials: "RV",
        rating: 5,
        course: "MERN Stack Development",
        role: "Node.js Developer",
        quote:
          "Being pushed to write tests early changed how I work. It came up in every interview I sat.",
      },
    ],
    faqs: [
      {
        q: "Who can join this course?",
        a: "Anyone comfortable with basic programming. If you have never written JavaScript, start with Full Stack Web Development instead — it covers the fundamentals first.",
      },
      {
        q: "What are the prerequisites?",
        a: "Basic programming logic and some HTML/CSS exposure. The first module refreshes the JavaScript you need.",
      },
      ...COMMON_FAQS,
    ],
    relatedCourses: ["full-stack-web-development", "java-programming", "python-programming", "data-analytics"],
    keywords: ["MERN stack course", "React training Hoshiarpur", "Node.js course", "MongoDB training"],
  },

  /* ------------------------------------------------------------------ */
  {
    slug: "python-programming",
    title: "Python Programming",
    shortDescription: "The language, properly — then automation, data and APIs with it.",
    overview:
      "Three months building genuine fluency in Python: the language itself, then the libraries that make it useful for automation, data work and backend services.",
    category: "Programming",
    level: "Beginner to Intermediate",
    duration: "3 Months",
    mode: "Online / Offline",
    certification: true,
    heroImage: "/images/ai.webp",
    video: {
      url: "",
      thumbnail: "/images/classroom.webp",
      caption: "What the first month looks like, and what you build in it.",
    },
    rating: { score: 4.8, count: 192 },
    audience: [A.beginners, A.students, A.professionals, A.switchers, A.entrepreneurs],
    whyChooseUs: COMMON_WHY,
    modules: [
      {
        title: "Python fundamentals",
        summary: "Syntax, types and control flow, with enough practice to make it automatic.",
        topics: ["Variables & types", "Control flow", "Functions", "Error handling"],
        duration: "3 weeks",
        lessons: 12,
      },
      {
        title: "Data structures",
        summary: "Lists, dicts, sets and when each is the right answer.",
        topics: ["Collections", "Comprehensions", "Iterators & generators", "Complexity basics"],
        duration: "2 weeks",
        lessons: 9,
      },
      {
        title: "Object-oriented Python",
        summary: "Structuring code that grows past a single file.",
        topics: ["Classes", "Inheritance", "Dunder methods", "Modules & packages"],
        duration: "2 weeks",
        lessons: 8,
      },
      {
        title: "Files, APIs and automation",
        summary: "Making Python do the tedious work.",
        topics: ["File I/O", "CSV & JSON", "requests", "Scheduling scripts"],
        duration: "2 weeks",
        lessons: 8,
      },
      {
        title: "Working with data",
        summary: "NumPy and Pandas for analysis you can act on.",
        topics: ["NumPy arrays", "Pandas dataframes", "Cleaning", "Plotting"],
        duration: "2 weeks",
        lessons: 8,
      },
      {
        title: "Backend with Django or Flask",
        summary: "Serving what you have built over HTTP.",
        topics: ["Routing", "Templates & JSON", "ORM basics", "Deployment"],
        duration: "3 weeks",
        lessons: 10,
      },
    ],
    learningOutcomes: [
      "Write clear, idiomatic Python",
      "Choose the right data structure for a problem",
      "Automate repetitive file and data tasks",
      "Consume and build REST APIs",
      "Clean and analyse data with Pandas",
      "Serve a small application with Django or Flask",
    ],
    tools: ["Python", "Pandas", "NumPy", "Flask", "Django", "SQLite", "Git", "GitHub", "VS Code", "Jupyter"],
    careerOutcomes: {
      roles: ["Python Developer", "Backend Developer", "Automation Engineer", "Data Analyst", "QA Automation Engineer"],
      opportunities: ["Backend teams", "Data and reporting roles", "Automation and scripting work", "Freelance tooling"],
      nextSteps: ["Data Analytics", "Machine learning foundations", "Django in depth", "Cloud & DevOps"],
      industries: ["Software products", "Analytics", "Operations & back office", "Research"],
    },
    projects: [
      {
        name: "Data cleaning pipeline",
        summary: "Take a messy real-world dataset and produce something reportable.",
        tech: ["Python", "Pandas"],
        level: "Intermediate",
        skills: ["Data cleaning", "Aggregation", "Reporting"],
        image: "/images/data-science.webp",
      },
      {
        name: "Web scraper & scheduler",
        summary: "Collect data on a schedule and store it for later analysis.",
        tech: ["Python", "requests", "SQLite"],
        level: "Intermediate",
        skills: ["HTTP", "Parsing", "Persistence"],
        image: "/images/cyber.webp",
      },
      {
        name: "REST API service",
        summary: "A small documented service with CRUD and validation.",
        tech: ["Flask", "SQLite"],
        level: "Beginner",
        skills: ["Routing", "Validation", "Testing"],
        image: "/images/cloud.webp",
      },
    ],
    instructor: DEFAULT_INSTRUCTOR,
    comparison: DEFAULT_COMPARISON,
    reviews: [
      {
        name: "Manpreet Singh",
        initials: "MS",
        rating: 5,
        course: "Python Programming",
        role: "Automation Engineer",
        quote:
          "I came in wanting to automate reports at work. By month two I had replaced three hours of manual work a week.",
      },
      {
        name: "Ritika Sharma",
        initials: "RS",
        rating: 5,
        course: "Python Programming",
        role: "Data Analyst",
        quote:
          "The data module was the turning point. Pandas stopped being intimidating once we used it on a real messy dataset.",
      },
    ],
    faqs: [
      {
        q: "Is this course suitable for beginners?",
        a: "Yes. It is designed as a first programming course and assumes nothing beyond basic computer use.",
      },
      {
        q: "What are the prerequisites?",
        a: "None. Bring a laptop and a willingness to practise between sessions.",
      },
      ...COMMON_FAQS,
    ],
    relatedCourses: ["data-analytics", "full-stack-web-development", "java-programming", "digital-marketing"],
    keywords: ["python course Hoshiarpur", "python training", "django flask course", "python for data analysis"],
  },

  /* ------------------------------------------------------------------ */
  {
    slug: "java-programming",
    title: "Java Programming",
    shortDescription: "Core Java through to Spring Boot services and JDBC-backed applications.",
    overview:
      "Four months on the language that still runs most enterprise backends. Core Java and OOP first, then collections, JDBC and Spring Boot, finishing with a service you have built and deployed.",
    category: "Programming",
    level: "Beginner to Advanced",
    duration: "4 Months",
    mode: "Online / Offline",
    certification: true,
    heroImage: "/images/cloud.webp",
    video: {
      url: "",
      thumbnail: "/images/lab.webp",
      caption: "How the Java track is structured across four months.",
    },
    rating: { score: 4.8, count: 137 },
    audience: [A.beginners, A.students, A.freshers, A.switchers],
    whyChooseUs: COMMON_WHY,
    modules: [
      {
        title: "Core Java",
        summary: "Syntax, types, control flow and the JVM model underneath.",
        topics: ["Types & operators", "Control flow", "Arrays & strings", "How the JVM runs code"],
        duration: "3 weeks",
        lessons: 14,
      },
      {
        title: "Object-oriented programming",
        summary: "The design ideas Java is built around.",
        topics: ["Classes & objects", "Inheritance", "Interfaces", "Polymorphism"],
        duration: "3 weeks",
        lessons: 12,
      },
      {
        title: "Collections & generics",
        summary: "The data structures every Java codebase uses.",
        topics: ["List, Set, Map", "Generics", "Streams", "Comparators"],
        duration: "3 weeks",
        lessons: 12,
      },
      {
        title: "Exceptions, files & JDBC",
        summary: "Talking to the outside world safely.",
        topics: ["Exception design", "File I/O", "JDBC", "SQL basics"],
        duration: "3 weeks",
        lessons: 12,
      },
      {
        title: "Spring Boot",
        summary: "Building a service the way teams actually do.",
        topics: ["Dependency injection", "REST controllers", "JPA", "Configuration"],
        duration: "4 weeks",
        lessons: 16,
      },
      {
        title: "Project & deployment",
        summary: "One backend service, reviewed and shipped.",
        topics: ["Layered architecture", "Testing", "Build tooling", "Deployment"],
        duration: "3 weeks",
        lessons: 10,
      },
    ],
    learningOutcomes: [
      "Write clean object-oriented Java",
      "Use collections and streams fluently",
      "Query a relational database from Java",
      "Build REST services with Spring Boot",
      "Structure a layered backend application",
      "Test and deploy a Java service",
    ],
    tools: ["Java", "Spring Boot", "JDBC", "JPA", "MySQL", "Maven", "JUnit", "Git", "GitHub", "IntelliJ IDEA"],
    careerOutcomes: {
      roles: ["Java Developer", "Backend Developer", "Software Engineer", "API Developer"],
      opportunities: ["Enterprise engineering teams", "Service and consulting firms", "Product backends", "Campus placements"],
      nextSteps: ["Microservices", "Cloud & DevOps", "System design", "Android with Kotlin"],
      industries: ["Banking & finance", "Enterprise software", "Telecom", "Government systems"],
    },
    projects: [
      {
        name: "Library management service",
        summary: "Catalogue, lending and returns over a relational database.",
        tech: ["Java", "Spring Boot", "MySQL"],
        level: "Intermediate",
        skills: ["JPA", "REST", "Validation"],
        image: "/images/classroom.webp",
      },
      {
        name: "Banking transactions API",
        summary: "Accounts, transfers and an audit trail, with tests around the money paths.",
        tech: ["Java", "Spring Boot", "JUnit"],
        level: "Advanced",
        skills: ["Transactions", "Testing", "Error handling"],
        image: "/images/cyber.webp",
      },
      {
        name: "Inventory console application",
        summary: "A first end-to-end build using collections and JDBC.",
        tech: ["Java", "JDBC"],
        level: "Beginner",
        skills: ["OOP", "Persistence", "CLI design"],
        image: "/images/lab.webp",
      },
    ],
    instructor: DEFAULT_INSTRUCTOR,
    comparison: DEFAULT_COMPARISON,
    reviews: [
      {
        name: "Gurpreet Sandhu",
        initials: "GS",
        rating: 5,
        course: "Java Programming",
        role: "Java Developer",
        quote:
          "Collections and streams were taught with real problems rather than toy examples. That is exactly what the interview asked about.",
      },
      {
        name: "Anjali Rana",
        initials: "AR",
        rating: 4,
        course: "Java Programming",
        role: "Backend Developer",
        quote:
          "Spring Boot felt enormous until the module broke it into pieces. Shipping the final service made it click.",
      },
    ],
    faqs: [
      {
        q: "Is this course suitable for beginners?",
        a: "Yes. Core Java starts from first principles, though the pace picks up once Spring Boot arrives.",
      },
      {
        q: "What are the prerequisites?",
        a: "None, beyond basic computer familiarity. Some programming exposure helps but is not assumed.",
      },
      ...COMMON_FAQS,
    ],
    relatedCourses: ["python-programming", "full-stack-web-development", "mern-stack-development", "data-analytics"],
    keywords: ["java course Hoshiarpur", "spring boot training", "core java classes", "java backend course"],
  },

  /* ------------------------------------------------------------------ */
  {
    slug: "data-analytics",
    title: "Data Analytics",
    shortDescription: "SQL, Python and dashboards that a business will actually act on.",
    overview:
      "Five months turning raw data into decisions: statistics you genuinely use, SQL you can be tested on, and dashboards built to answer a specific business question rather than to look busy.",
    category: "Data & AI",
    level: "Beginner to Advanced",
    duration: "5 Months",
    mode: "Online / Offline",
    certification: true,
    heroImage: "/images/data-science.webp",
    video: {
      url: "",
      thumbnail: "/images/form.webp",
      caption: "The analytics workflow, from raw table to reported insight.",
    },
    rating: { score: 4.9, count: 156 },
    audience: [A.beginners, A.students, A.professionals, A.switchers, A.entrepreneurs],
    whyChooseUs: COMMON_WHY,
    modules: [
      {
        title: "Excel & analytical thinking",
        summary: "Framing a question before touching a tool.",
        topics: ["Pivot tables", "Lookup functions", "Data hygiene", "Framing an analysis"],
        duration: "2 weeks",
        lessons: 8,
      },
      {
        title: "SQL",
        summary: "Getting exactly the rows you need out of a real database.",
        topics: ["SELECT & filtering", "Joins", "Window functions", "Query performance"],
        duration: "4 weeks",
        lessons: 16,
      },
      {
        title: "Python for analysis",
        summary: "Pandas for the work spreadsheets cannot carry.",
        topics: ["Dataframes", "Cleaning", "Merging", "Time series"],
        duration: "4 weeks",
        lessons: 16,
      },
      {
        title: "Statistics that matter",
        summary: "Enough inference to avoid confident wrong answers.",
        topics: ["Distributions", "Hypothesis testing", "A/B testing", "Correlation vs causation"],
        duration: "3 weeks",
        lessons: 12,
      },
      {
        title: "Power BI & Tableau",
        summary: "Dashboards designed for the person who has to decide something.",
        topics: ["Data modelling", "DAX basics", "Visual design", "Publishing & refresh"],
        duration: "4 weeks",
        lessons: 14,
      },
      {
        title: "Capstone analysis",
        summary: "One end-to-end analysis, presented and defended.",
        topics: ["Problem framing", "Analysis", "Storytelling", "Presentation"],
        duration: "3 weeks",
        lessons: 10,
      },
    ],
    learningOutcomes: [
      "Write SQL against a real schema with confidence",
      "Clean and reshape messy data in Pandas",
      "Choose the right chart for the question",
      "Run and interpret a basic experiment",
      "Build dashboards in Power BI and Tableau",
      "Present findings so a decision follows",
    ],
    tools: ["SQL", "MySQL", "Python", "Pandas", "NumPy", "Power BI", "Tableau", "Excel", "Git", "Jupyter"],
    careerOutcomes: {
      roles: ["Data Analyst", "Business Analyst", "BI Developer", "Reporting Analyst", "Analytics Consultant"],
      opportunities: ["Analytics teams", "Operations and finance reporting", "Freelance dashboard work", "Consulting"],
      nextSteps: ["Machine learning foundations", "Data engineering basics", "Advanced statistics", "Cloud data platforms"],
      industries: ["Retail & e-commerce", "Finance", "Healthcare", "Logistics"],
    },
    projects: [
      {
        name: "Sales analytics dashboard",
        summary: "Revenue, cohorts and regional performance in one publishable dashboard.",
        tech: ["SQL", "Power BI"],
        level: "Intermediate",
        skills: ["Data modelling", "Visual design", "DAX"],
        image: "/images/data-science.webp",
      },
      {
        name: "Customer churn analysis",
        summary: "Find who leaves, when, and which signals precede it.",
        tech: ["Python", "Pandas", "SQL"],
        level: "Advanced",
        skills: ["Feature analysis", "Segmentation", "Reporting"],
        image: "/images/ai.webp",
      },
      {
        name: "Pricing experiment review",
        summary: "Read an A/B test properly and say what it does and does not prove.",
        tech: ["Python", "Statistics"],
        level: "Intermediate",
        skills: ["Hypothesis testing", "Interpretation", "Communication"],
        image: "/images/digital.webp",
      },
    ],
    instructor: DEFAULT_INSTRUCTOR,
    comparison: DEFAULT_COMPARISON,
    reviews: [
      {
        name: "Simranjeet Kaur",
        initials: "SK",
        rating: 5,
        course: "Data Analytics",
        role: "Data Analyst",
        quote:
          "The SQL and statistics modules were relentless, and that is exactly why the interview felt easy.",
      },
      {
        name: "Deepak Chauhan",
        initials: "DC",
        rating: 5,
        course: "Data Analytics",
        role: "BI Developer",
        quote:
          "Being made to present the capstone to a room changed how I build dashboards. I design for the decision now.",
      },
    ],
    faqs: [
      {
        q: "Is this course suitable for beginners?",
        a: "Yes. It starts with Excel and analytical framing before SQL, so no prior coding is assumed.",
      },
      {
        q: "What are the prerequisites?",
        a: "Comfort with numbers and basic spreadsheets. Programming experience is helpful but not required.",
      },
      ...COMMON_FAQS,
    ],
    relatedCourses: ["python-programming", "digital-marketing", "full-stack-web-development", "java-programming"],
    keywords: ["data analytics course Hoshiarpur", "power bi training", "sql course", "data analyst training"],
  },

  /* ------------------------------------------------------------------ */
  {
    slug: "digital-marketing",
    title: "Digital Marketing",
    shortDescription: "Run real campaigns with a real budget, then report on them properly.",
    overview:
      "Four months of performance marketing: SEO, paid social, Google Ads and analytics, taught by running live campaigns and reporting on them the way an agency lead expects.",
    category: "Marketing",
    level: "Beginner to Advanced",
    duration: "4 Months",
    mode: "Online / Offline",
    certification: true,
    heroImage: "/images/digital.webp",
    video: {
      url: "",
      thumbnail: "/images/classroom.webp",
      caption: "How live campaign work is built into the programme.",
    },
    rating: { score: 4.8, count: 143 },
    audience: [A.beginners, A.students, A.freshers, A.freelancers, A.entrepreneurs],
    whyChooseUs: COMMON_WHY,
    modules: [
      {
        title: "Marketing foundations",
        summary: "Audience, positioning and the funnel everything else hangs on.",
        topics: ["Audience research", "Positioning", "Funnel stages", "Offer design"],
        duration: "2 weeks",
        lessons: 8,
      },
      {
        title: "SEO",
        summary: "Earning traffic that keeps arriving after you stop paying.",
        topics: ["Keyword research", "On-page SEO", "Technical audit", "Link building"],
        duration: "4 weeks",
        lessons: 16,
      },
      {
        title: "Google Ads",
        summary: "Search and shopping campaigns run against a real budget.",
        topics: ["Campaign structure", "Keyword match types", "Ad copy testing", "Bidding"],
        duration: "3 weeks",
        lessons: 12,
      },
      {
        title: "Social & content",
        summary: "Meta and organic content that earns attention rather than buying all of it.",
        topics: ["Meta Ads", "Creative testing", "Content calendars", "Community"],
        duration: "3 weeks",
        lessons: 12,
      },
      {
        title: "Analytics & attribution",
        summary: "Tying spend to outcomes without fooling yourself.",
        topics: ["GA4", "Events & conversions", "Attribution models", "Reporting"],
        duration: "3 weeks",
        lessons: 12,
      },
      {
        title: "Live campaign & report",
        summary: "Plan, run and defend one campaign end to end.",
        topics: ["Budget planning", "Execution", "Optimisation", "Client reporting"],
        duration: "3 weeks",
        lessons: 10,
      },
    ],
    learningOutcomes: [
      "Research an audience and position an offer",
      "Run search and social campaigns end to end",
      "Audit and improve a site's organic performance",
      "Set up GA4 events and conversion tracking",
      "Read attribution without over-claiming",
      "Report campaign performance to a client or manager",
    ],
    tools: ["Google Ads", "Meta Ads Manager", "GA4", "Google Search Console", "SEMrush", "WordPress", "Canva", "Looker Studio"],
    careerOutcomes: {
      roles: ["Performance Marketer", "SEO Specialist", "Social Media Manager", "Campaign Manager", "Growth Analyst"],
      opportunities: ["Agency roles", "In-house marketing teams", "Freelance campaign management", "Running your own business's marketing"],
      nextSteps: ["Marketing automation", "Conversion rate optimisation", "Data Analytics", "Content strategy"],
      industries: ["E-commerce", "EdTech", "Local services", "D2C brands"],
    },
    projects: [
      {
        name: "Full-funnel campaign",
        summary: "A live campaign with a real budget, from brief through to performance report.",
        tech: ["Google Ads", "Meta Ads", "GA4"],
        level: "Advanced",
        skills: ["Budgeting", "Creative testing", "Reporting"],
        image: "/images/digital.webp",
      },
      {
        name: "SEO audit and rebuild",
        summary: "Audit a real site, fix what matters, and measure the movement.",
        tech: ["Search Console", "SEMrush", "WordPress"],
        level: "Intermediate",
        skills: ["Technical SEO", "Content planning", "Measurement"],
        image: "/images/classroom.webp",
      },
      {
        name: "Landing page CRO test",
        summary: "Build two variants, run the test, and interpret the result honestly.",
        tech: ["WordPress", "GA4"],
        level: "Intermediate",
        skills: ["Copywriting", "Experiment design", "Analysis"],
        image: "/images/form.webp",
      },
    ],
    instructor: DEFAULT_INSTRUCTOR,
    comparison: DEFAULT_COMPARISON,
    reviews: [
      {
        name: "Priya Bansal",
        initials: "PB",
        rating: 5,
        course: "Digital Marketing",
        role: "Performance Marketer",
        quote:
          "Running a campaign with actual money on the line taught me more in three weeks than a year of reading.",
      },
      {
        name: "Karan Thakur",
        initials: "KT",
        rating: 5,
        course: "Digital Marketing",
        role: "SEO Specialist",
        quote:
          "The audit module gave me a repeatable process. I use the same checklist with freelance clients now.",
      },
    ],
    faqs: [
      {
        q: "Is this course suitable for beginners?",
        a: "Yes. It starts with marketing fundamentals before any platform work, so no prior experience is needed.",
      },
      {
        q: "Do I need my own ad budget?",
        a: "No. Live campaign work runs on a supervised budget provided as part of the programme.",
      },
      ...COMMON_FAQS,
    ],
    relatedCourses: ["data-analytics", "python-programming", "full-stack-web-development", "mern-stack-development"],
    keywords: ["digital marketing course Hoshiarpur", "seo training", "google ads course", "performance marketing training"],
  },
];
