import {
  COMMON_AUDIENCE as A, COMMON_FAQS, COMMON_WHY, DEFAULT_INSTRUCTOR,
} from "./shared";
import type { Course } from "./types";

/** AI and analytics tracks that sit alongside Data Analytics in the catalogue. */
export const DATA_AI_COURSES: Course[] = [
  {
    slug: "artificial-intelligence",
    title: "Artificial Intelligence",
    shortDescription: "From the maths underneath to a model running in production.",
    overview:
      "Six months across the AI stack: the statistics that make models behave, the libraries that build them, and the deployment work that turns a notebook into something a business can use.",
    category: "AI",
    badge: "Trending",
    level: "Intermediate to Advanced",
    duration: "6 Months",
    mode: "Online / Offline",
    certification: true,
    heroImage: "/images/ai.webp",
    video: { url: "", thumbnail: "/images/classroom.webp", caption: "How the AI track is structured." },
    rating: { score: 4.9, count: 128 },
    audience: [A.students, A.freshers, A.professionals, A.switchers],
    whyChooseUs: COMMON_WHY,
    modules: [
      { title: "Maths for AI", summary: "The linear algebra, calculus and probability you actually use.", topics: ["Vectors & matrices", "Gradients", "Probability", "Distributions"], duration: "3 weeks", lessons: 12 },
      { title: "Python for AI", summary: "NumPy, Pandas and the tooling around them.", topics: ["NumPy", "Pandas", "Visualisation", "Notebooks"], duration: "3 weeks", lessons: 12 },
      { title: "Machine learning core", summary: "Supervised and unsupervised methods that hold up.", topics: ["Regression", "Classification", "Clustering", "Validation"], duration: "5 weeks", lessons: 20 },
      { title: "Deep learning", summary: "Neural networks, and when they are worth the cost.", topics: ["Neural networks", "CNNs", "Sequence models", "Transfer learning"], duration: "5 weeks", lessons: 20 },
      { title: "LLMs & applied AI", summary: "Working with large models rather than training them from scratch.", topics: ["Prompting", "Embeddings", "RAG", "Evaluation"], duration: "4 weeks", lessons: 16 },
      { title: "Deployment", summary: "Getting a model to where it is useful.", topics: ["APIs", "Containers", "Monitoring", "Model drift"], duration: "4 weeks", lessons: 14 },
    ],
    learningOutcomes: [
      "Frame a problem as a learning task",
      "Build and validate models without fooling yourself",
      "Train neural networks for vision and text",
      "Use LLMs with retrieval over your own data",
      "Deploy and monitor a model in production",
    ],
    tools: ["Python", "NumPy", "Pandas", "scikit-learn", "PyTorch", "TensorFlow", "Hugging Face", "Docker", "FastAPI"],
    careerOutcomes: {
      roles: ["AI Developer", "ML Engineer", "Applied Scientist", "Data Scientist"],
      opportunities: ["Product AI teams", "Research assistance", "Consulting", "Freelance model work"],
      nextSteps: ["MLOps", "Computer vision in depth", "NLP specialisation", "Cloud & DevOps"],
      industries: ["SaaS", "Healthcare", "Manufacturing", "Fintech"],
    },
    projects: [
      { name: "Document Q&A with RAG", summary: "Retrieval over a private corpus with evaluated answers.", tech: ["Python", "Embeddings", "LLM"], level: "Advanced", skills: ["Retrieval", "Evaluation", "Prompting"], image: "/images/ai.webp" },
      { name: "Defect detection model", summary: "A vision model trained on a production line dataset.", tech: ["PyTorch", "OpenCV"], level: "Advanced", skills: ["CNNs", "Augmentation", "Metrics"], image: "/images/lab.webp" },
    ],
    instructor: DEFAULT_INSTRUCTOR,
    reviews: [],
    faqs: [
      { q: "Is this course suitable for beginners?", a: "It assumes some programming. If you have never written Python, start with Python Programming and move across after." },
      { q: "What are the prerequisites?", a: "Comfort with Python basics and school-level maths. The first module rebuilds the maths you need." },
      ...COMMON_FAQS,
    ],
    relatedCourses: ["machine-learning", "data-analytics", "tableau", "python-programming"],
    keywords: ["artificial intelligence course Hoshiarpur", "ai training", "deep learning course", "llm course"],
  },
  {
    slug: "machine-learning",
    title: "Machine Learning",
    shortDescription: "Build, validate and ship models that behave on data they have not seen.",
    overview:
      "Four months on the core of applied ML: feature work, model selection, honest validation, and the deployment step most courses skip.",
    category: "Data & AI",
    level: "Intermediate",
    duration: "4 Months",
    mode: "Online / Offline",
    certification: true,
    heroImage: "/images/ai.webp",
    video: { url: "", thumbnail: "/images/form.webp", caption: "What the ML track covers, week by week." },
    rating: { score: 4.8, count: 114 },
    audience: [A.students, A.freshers, A.professionals, A.switchers],
    whyChooseUs: COMMON_WHY,
    modules: [
      { title: "Foundations", summary: "Python, data handling and the statistics ML rests on.", topics: ["Pandas", "Distributions", "Sampling", "Bias & variance"], duration: "3 weeks", lessons: 12 },
      { title: "Supervised learning", summary: "Regression and classification, properly validated.", topics: ["Linear models", "Trees", "Ensembles", "Cross-validation"], duration: "4 weeks", lessons: 16 },
      { title: "Unsupervised learning", summary: "Structure without labels.", topics: ["Clustering", "Dimensionality reduction", "Anomalies", "Segmentation"], duration: "3 weeks", lessons: 12 },
      { title: "Feature engineering", summary: "Where most of the real gains come from.", topics: ["Encoding", "Scaling", "Selection", "Leakage"], duration: "3 weeks", lessons: 12 },
      { title: "Deployment & monitoring", summary: "A model that keeps working after launch.", topics: ["APIs", "Batch scoring", "Drift", "Retraining"], duration: "3 weeks", lessons: 10 },
    ],
    learningOutcomes: [
      "Choose a model that fits the problem",
      "Engineer features without leaking the target",
      "Validate honestly with cross-validation",
      "Explain a model to a non-technical stakeholder",
      "Deploy and monitor a model in production",
    ],
    tools: ["Python", "scikit-learn", "Pandas", "NumPy", "XGBoost", "MLflow", "FastAPI", "Jupyter"],
    careerOutcomes: {
      roles: ["ML Engineer", "Data Scientist", "Applied ML Developer", "Analytics Engineer"],
      opportunities: ["Product data teams", "Analytics consultancies", "Research support", "Freelance modelling"],
      nextSteps: ["Deep learning", "MLOps", "Artificial Intelligence", "Cloud & DevOps"],
      industries: ["E-commerce", "Fintech", "Logistics", "Healthcare"],
    },
    projects: [
      { name: "Churn prediction model", summary: "Predict churn, then explain which signals drive it.", tech: ["scikit-learn", "Pandas"], level: "Intermediate", skills: ["Feature engineering", "Validation", "Explainability"], image: "/images/data-science.webp" },
      { name: "Recommendation engine", summary: "A collaborative filtering recommender, evaluated offline.", tech: ["Python", "NumPy"], level: "Advanced", skills: ["Similarity", "Evaluation", "Cold start"], image: "/images/ai.webp" },
    ],
    instructor: DEFAULT_INSTRUCTOR,
    reviews: [],
    faqs: [
      { q: "Is this course suitable for beginners?", a: "It assumes basic Python. Absolute beginners should take Python Programming first." },
      { q: "What are the prerequisites?", a: "Python fundamentals and school-level statistics. The first module covers the rest." },
      ...COMMON_FAQS,
    ],
    relatedCourses: ["artificial-intelligence", "data-analytics", "python-programming", "tableau"],
    keywords: ["machine learning course Hoshiarpur", "ml training", "scikit-learn course", "predictive modelling course"],
  },
  {
    slug: "tableau",
    title: "Tableau",
    shortDescription: "Dashboards a business will actually act on, built on real data models.",
    overview:
      "Six weeks turning data into decisions in Tableau: connecting and shaping sources, choosing the right visual, and publishing dashboards people return to.",
    category: "Data & AI",
    level: "Beginner to Intermediate",
    duration: "6 Weeks",
    mode: "Online / Offline",
    certification: true,
    heroImage: "/images/data-science.webp",
    video: { url: "", thumbnail: "/images/form.webp", caption: "Building a dashboard from a raw extract." },
    rating: { score: 4.8, count: 96 },
    audience: [A.beginners, A.students, A.professionals, A.entrepreneurs],
    whyChooseUs: COMMON_WHY,
    modules: [
      { title: "Connecting & shaping data", summary: "Getting clean, joined data into Tableau.", topics: ["Connections", "Joins & blends", "Extracts", "Data prep"], duration: "1 week", lessons: 5 },
      { title: "Core visualisations", summary: "Choosing the chart the question deserves.", topics: ["Bar & line", "Maps", "Scatter", "Chart choice"], duration: "2 weeks", lessons: 8 },
      { title: "Calculations & LOD", summary: "Where Tableau gets genuinely powerful.", topics: ["Calculated fields", "Table calcs", "LOD expressions", "Parameters"], duration: "2 weeks", lessons: 8 },
      { title: "Dashboards & publishing", summary: "Layout, interactivity and getting it in front of people.", topics: ["Actions", "Filters", "Layout", "Tableau Public / Server"], duration: "1 week", lessons: 5 },
    ],
    learningOutcomes: [
      "Connect, join and extract from real sources",
      "Choose the right chart for the question",
      "Write calculated fields and LOD expressions",
      "Build interactive dashboards with actions",
      "Publish and share dashboards that stay current",
    ],
    tools: ["Tableau Desktop", "Tableau Public", "SQL", "Excel", "Tableau Prep"],
    careerOutcomes: {
      roles: ["BI Developer", "Data Analyst", "Reporting Analyst", "Visualisation Specialist"],
      opportunities: ["Analytics teams", "Finance and operations reporting", "Freelance dashboard work", "Consulting"],
      nextSteps: ["Power BI", "Data Analytics", "SQL in depth", "Machine Learning"],
      industries: ["Retail", "Finance", "Healthcare", "Logistics"],
    },
    projects: [
      { name: "Sales performance dashboard", summary: "Revenue, region and cohort views in one publishable dashboard.", tech: ["Tableau", "SQL"], level: "Intermediate", skills: ["Data modelling", "LOD", "Layout"], image: "/images/data-science.webp" },
      { name: "Operations KPI board", summary: "A live-refreshing board built for a daily stand-up.", tech: ["Tableau Prep", "Tableau"], level: "Beginner", skills: ["Data prep", "Chart choice", "Publishing"], image: "/images/digital.webp" },
    ],
    instructor: DEFAULT_INSTRUCTOR,
    reviews: [],
    faqs: [
      { q: "Is this course suitable for beginners?", a: "Yes. It starts from connecting a spreadsheet and assumes no prior BI experience." },
      { q: "What are the prerequisites?", a: "Comfort with spreadsheets. SQL helps but is introduced where it is needed." },
      ...COMMON_FAQS,
    ],
    relatedCourses: ["data-analytics", "machine-learning", "artificial-intelligence", "digital-marketing"],
    keywords: ["tableau course Hoshiarpur", "tableau training", "data visualisation course", "bi dashboard course"],
  },
];
