import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

/**
 * ESLint flat config.
 *
 * `next lint` is deprecated in Next.js 15 and removed in 16, so the project
 * runs the ESLint CLI directly (see the "lint" script). FlatCompat is what
 * lets the still-eslintrc-style `eslint-config-next` load under flat config.
 */
const compat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url)),
});

const config = [
  {
    ignores: [
      ".next/**",
      "out/**",
      "node_modules/**",
      "next-env.d.ts",
      // Generated by `prisma generate`; not ours to lint.
      "src/generated/**",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
];

export default config;
